import XCTest
import Crypto
@testable import PodiumCore

/// Coverage of `VAPIDKeyStore` — key generation, the on-disk file format
/// (must stay byte-compatible with Node's `web-push` `vapid-keys.json`, per
/// P4.2's brief), and the VAPID JWT header it signs.
///
/// IMPORTANT: every test here uses its own temp directory. NEVER point this
/// suite at `~/.claude/podium/data/vapid-keys.json` — that's the user's real
/// (possibly live) key file (see STANDALONE_PLAN.md §7 environment quirks).
final class VAPIDKeysTests: XCTestCase {
    private var tempDir: URL!

    override func setUpWithError() throws {
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("podium-vapid-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: tempDir)
    }

    // MARK: - Generation

    func testGenerateProducesValidP256KeyPair() throws {
        let pair = VAPIDKeyStore.generate()

        // publicKey: 65-byte uncompressed P-256 point, base64url.
        let publicRaw = Base64URL.decode(pair.publicKey)
        XCTAssertEqual(publicRaw?.count, 65)
        XCTAssertEqual(publicRaw?.first, 0x04, "uncompressed EC point must start with 0x04")

        // privateKey: 32-byte raw scalar, base64url.
        let privateRaw = Base64URL.decode(pair.privateKey)
        XCTAssertEqual(privateRaw?.count, 32)

        // Both must be usable as actual P256 keys.
        XCTAssertNoThrow(try VAPIDKeyStore.publicKeyAgreementKey(from: pair))
        XCTAssertNoThrow(try VAPIDKeyStore.signingPrivateKey(from: pair))
    }

    func testGeneratedPublicAndPrivateKeysAreAMatchingPair() throws {
        let pair = VAPIDKeyStore.generate()
        let signingPrivate = try VAPIDKeyStore.signingPrivateKey(from: pair)
        let derivedPublicBase64URL = Base64URL.encode(signingPrivate.publicKey.x963Representation)
        XCTAssertEqual(derivedPublicBase64URL, pair.publicKey)
    }

    // MARK: - loadOrCreate: first run creates + persists

    func testLoadOrCreateGeneratesAndPersistsWhenFileMissing() throws {
        let path = tempDir.appendingPathComponent("nested/dir/vapid-keys.json")
        XCTAssertFalse(FileManager.default.fileExists(atPath: path.path))

        let created = try VAPIDKeyStore.loadOrCreate(path: path)
        XCTAssertTrue(FileManager.default.fileExists(atPath: path.path))

        let reloaded = try VAPIDKeyStore.loadOrCreate(path: path)
        XCTAssertEqual(created, reloaded, "a second load must return the persisted pair, not regenerate")
    }

    // MARK: - Node web-push vapid-keys.json format round trip

    /// Byte-for-byte the shape `webpush.generateVAPIDKeys()` writes:
    /// `{ "publicKey": "...", "privateKey": "..." }`, camelCase, no other
    /// fields. Loading a file written in exactly that shape (as if migrating
    /// off the Node plugin) must succeed and produce usable keys.
    func testLoadsNodeWebPushVapidKeysJSONFormat() throws {
        // A real key pair (not just fixture strings) so downstream signing
        // actually exercises valid EC points, generated once via our own
        // generator (equivalent shape to what Node's web-push would write).
        let genuinePair = VAPIDKeyStore.generate()
        let nodeStyleJSON = """
        {
          "publicKey": "\(genuinePair.publicKey)",
          "privateKey": "\(genuinePair.privateKey)"
        }
        """
        let path = tempDir.appendingPathComponent("vapid-keys.json")
        try Data(nodeStyleJSON.utf8).write(to: path)

        let loaded = try VAPIDKeyStore.loadOrCreate(path: path)
        XCTAssertEqual(loaded.publicKey, genuinePair.publicKey)
        XCTAssertEqual(loaded.privateKey, genuinePair.privateKey)

        // File must NOT have been rewritten/regenerated by the load.
        let stillOnDisk = try String(contentsOf: path, encoding: .utf8)
        XCTAssertTrue(stillOnDisk.contains(genuinePair.publicKey))
    }

    /// The on-disk shape our own `generate()` + `loadOrCreate` persist must
    /// itself decode under a plain camelCase `JSONDecoder` (i.e. exactly the
    /// shape web-push's Node library expects) — round trip in the other
    /// direction from the test above.
    func testPersistedFileDecodesUnderPlainCamelCaseDecoder() throws {
        let path = tempDir.appendingPathComponent("vapid-keys.json")
        let pair = try VAPIDKeyStore.loadOrCreate(path: path)

        let data = try Data(contentsOf: path)
        struct PlainShape: Decodable {
            let publicKey: String
            let privateKey: String
        }
        let decoded = try JSONDecoder().decode(PlainShape.self, from: data)
        XCTAssertEqual(decoded.publicKey, pair.publicKey)
        XCTAssertEqual(decoded.privateKey, pair.privateKey)
    }

    func testLoadOrCreateThrowsOnMalformedStoredFile() throws {
        let path = tempDir.appendingPathComponent("vapid-keys.json")
        try Data("not json at all".utf8).write(to: path)

        XCTAssertThrowsError(try VAPIDKeyStore.loadOrCreate(path: path)) { error in
            XCTAssertEqual(error as? VAPIDKeyError, .invalidStoredFile)
        }
    }

    // MARK: - VAPID JWT header/claims shape

    func testAuthorizationHeaderHasVapidSchemeWithJWTAndPublicKey() throws {
        let pair = VAPIDKeyStore.generate()
        let header = try VAPID.authorizationHeader(
            endpoint: "https://push.example.net/push/abc123",
            subject: "mailto:test@example.com",
            keys: pair
        )

        XCTAssertTrue(header.hasPrefix("vapid t="), "must use the `vapid` auth scheme")
        XCTAssertTrue(header.contains(", k=\(pair.publicKey)"), "must embed the raw public key as `k=`")

        // Extract the JWT and check its three-segment shape + claims.
        guard let tRange = header.range(of: "t="), let commaRange = header.range(of: ", k=") else {
            return XCTFail("could not locate t=/k= segments")
        }
        let jwt = String(header[tRange.upperBound..<commaRange.lowerBound])
        let segments = jwt.split(separator: ".")
        XCTAssertEqual(segments.count, 3, "JWT must have header.payload.signature")

        guard let headerData = Base64URL.decode(String(segments[0])),
              let payloadData = Base64URL.decode(String(segments[1]))
        else {
            return XCTFail("JWT header/payload segments did not decode as base64url")
        }

        let headerJSON = try JSONSerialization.jsonObject(with: headerData) as? [String: String]
        XCTAssertEqual(headerJSON?["typ"], "JWT")
        XCTAssertEqual(headerJSON?["alg"], "ES256")

        let payloadJSON = try JSONSerialization.jsonObject(with: payloadData) as? [String: Any]
        XCTAssertEqual(payloadJSON?["aud"] as? String, "https://push.example.net")
        XCTAssertEqual(payloadJSON?["sub"] as? String, "mailto:test@example.com")
        XCTAssertNotNil(payloadJSON?["exp"] as? Int)

        // Signature must be raw ECDSA (r||s, 64 bytes), not DER.
        guard let signatureData = Base64URL.decode(String(segments[2])) else {
            return XCTFail("signature segment did not decode as base64url")
        }
        XCTAssertEqual(signatureData.count, 64, "VAPID JWT signature must be the compact r||s form, not DER")
    }

    func testAuthorizationHeaderAudienceIncludesPortWhenPresent() throws {
        let pair = VAPIDKeyStore.generate()
        let header = try VAPID.authorizationHeader(
            endpoint: "https://push.example.net:8443/push/abc123",
            subject: "mailto:test@example.com",
            keys: pair
        )
        guard let tRange = header.range(of: "t="), let commaRange = header.range(of: ", k=") else {
            return XCTFail("could not locate t=/k= segments")
        }
        let jwt = String(header[tRange.upperBound..<commaRange.lowerBound])
        let payloadSegment = jwt.split(separator: ".")[1]
        guard let payloadData = Base64URL.decode(String(payloadSegment)) else {
            return XCTFail("payload segment did not decode")
        }
        let payloadJSON = try JSONSerialization.jsonObject(with: payloadData) as? [String: Any]
        XCTAssertEqual(payloadJSON?["aud"] as? String, "https://push.example.net:8443")
    }

    func testAuthorizationHeaderRejectsInvalidEndpoint() throws {
        let pair = VAPIDKeyStore.generate()
        XCTAssertThrowsError(try VAPID.authorizationHeader(endpoint: "not-a-url", subject: "mailto:a@b.com", keys: pair)) { error in
            XCTAssertEqual(error as? VAPIDError, .invalidAudience)
        }
    }
}
